# Agent info
template_root = "bcgov.index.html"
name = "BC Ministry of Finance"
abbreviation = "Ministry of Finance"
jurisdiction_name = "British Columbia"
jurisdiction_abbreviation = "BC"

# Webpage info
title = "Ministry of Finance"
description = "This is a description"
explanation = "Use the form below to obtain a PST number."

# Forms:
# 
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "pst_number"
title = "PST Number"

  [[forms.hidden]]
  name = "schema"
  value = "pst_number.ministry_of_finance"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_entity_id"
  pretty = "Legal Entity ID"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_name"
  pretty = "Legal Name"

  [[forms.inputs]]
  type = "text"
  required = false
  name = "doing_business_as_name"
  pretty = "Doing Business As Name"


# Schema mappers:
# 
# One for each schema type.
# 
# Each mapper is invoked when a request is received
# which contains value "schema" which maps to "for"
# property.

[[schema_mappers]]
for = "pst_number.ministry_of_finance"

  [[schema_mappers.attributes]]
  name = "legal_entity_id"
  from ="request"
  source = "legal_entity_id"

  [[schema_mappers.attributes]]
  name = "legal_name"
  from ="request"
  source = "legal_name"

  [[schema_mappers.attributes]]
  name = "doing_business_as_name"
  from ="request"
  source = "doing_business_as_name"

  [[schema_mappers.attributes]]
  name = "pst_number"
  from ="helper"
  source = "pst"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="helper"
  source = "now"

  [[schema_mappers.attributes]]
  name = "end_date"
  from ="helper"
  source = "one_year"

