# Agent info
template_root = "city_of_surrey.index.html"
name = "City of Surrey"
abbreviation = "Surrey"
jurisdiction_name = "Surrey"
jurisdiction_abbreviation = "SUR"

# Webpage info
title = "City of Surrey"
description = "Business Licensing"
explanation = "To conduct your business in Surrey, you must have a valid business licence."

# Forms:
#
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "business_license"
title = "Business License"

  [[forms.hidden]]
  name = "schema"
  value = "business_license.city_of_surrey"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_entity_id"
  pretty = "Legal Entity ID"

  [[forms.inputs]]
  type = "number"
  required = true
  name = "number_of_employees"
  pretty = "Number of Employees"

  [[forms.inputs]]
  type = "date"
  required = true
  name = "effective_date"
  pretty = "Effective Date"


# Schema mappers:
#
# One for each schema type.
#
# Each mapper is invoked when a request is received
# which contains value "schema" which maps to "for"
# property.

[[schema_mappers]]
for = "business_license.city_of_surrey"

  [[schema_mappers.attributes]]
  name = "legal_entity_id"
  from ="request"
  source = "legal_entity_id"

  [[schema_mappers.attributes]]
  name = "number_of_employees"
  from ="request"
  source = "number_of_employees"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="request"
  source = "effective_date"

  [[schema_mappers.attributes]]
  name = "end_date"
  from ="helper"
  source = "one_year"
